name: Project CI/CD & Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP + Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: json, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: Copy env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Modify Database for testing
        run: |
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env || echo "DB_CONNECTION=sqlite" >> .env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=:memory:/' .env || echo "DB_DATABASE=:memory:" >> .env

      - name: Create SQLite DB for testing
        run: touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --env=testing --no-interaction

      - name: Run tests + code coverage
        run: php artisan test
