name: Project CI/CD & Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP + Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: json, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: Copy env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Modify Database for testing
        run: |
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env || echo "DB_CONNECTION=sqlite" >> .env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=:memory:/' .env || echo "DB_DATABASE=:memory:" >> .env

      - name: Create SQLite DB for testing
        run: touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --env=testing --no-interaction

      - name: Run tests + code coverage
        run: php artisan test

      - env:
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit --coverage-html coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Prepare zip file for EB deploy
        if: success() && github.ref == 'refs/heads/main'
        run: zip -r app.zip . -x "*.git*" "*.github/*" "*.env" "coverage/*" ".phpunit.result.cache" "vendor/*" "tests/*"

      - name: Deploy to AWS Elastic Beanstalk
        if: success() && github.ref == 'refs/heads/main'
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: app.zip
